# Generated by Django 6.1 on 2026-08-31 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=255)),
                ('agency_url', models.URLField(blank=True, null=True)),
                ('agency_timezone', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('stop_code', models.CharField(blank=True, max_length=50, null=True)),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('stop_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('stop_url', models.URLField(blank=True, null=True)),
                ('wheelchair_boarding', models.IntegerField(blank=True, null=True)),
                ('location_type', models.IntegerField(blank=True, null=True)),
                ('parent_station', models.CharField(blank=True, max_length=50, null=True)),
                ('level_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(max_length=50)),
                ('route_long_name', models.CharField(max_length=255)),
                ('route_desc', models.TextField(blank=True, null=True)),
                ('route_type', models.IntegerField()),
                ('route_url', models.URLField(blank=True, null=True)),
                ('route_color', models.CharField(blank=True, max_length=6, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=6, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='transit.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('service_id', models.CharField(max_length=50)),
                ('trip_headsign', models.CharField(blank=True, max_length=255, null=True)),
                ('direction_id', models.IntegerField(blank=True, null=True)),
                ('shape_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wheelchair_accessible', models.IntegerField(blank=True, null=True)),
                ('bikes_allowed', models.IntegerField(blank=True, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transit.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('stop_sequence', models.IntegerField()),
                ('pickup_type', models.IntegerField(blank=True, null=True)),
                ('drop_off_type', models.IntegerField(blank=True, null=True)),
                ('timepoint', models.IntegerField(blank=True, null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_times', to='transit.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transit.trip')),
            ],
            options={
                'ordering': ['trip', 'stop_sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'stop_sequence'), name='unique_trip_stop_sequence')],
            },
        ),
    ]
